import { jsPDF } from "jspdf";
import "jspdf-autotable";

const generateMedicalReport = ({
  patientName,
  patientId,
  dob,
  gender,
  doctorName,
  prediction,
  confidence,
  category,
  severity,
  symptoms,
  causes,
  treatments,
  base64Image,
}) => {
  const doc = new jsPDF();

  // **HEADER SECTION**
  doc.setFillColor(106, 13, 173); // Violet Background
  doc.rect(0, 0, 210, 20, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text("Companion Care - Medical Report", 105, 13, { align: "center" });

  doc.setTextColor(0, 0, 0); // Reset text color

  // **PATIENT DETAILS**
  doc.setFontSize(12);
  doc.text("Patient Details", 15, 30);
  doc.autoTable({
    startY: 35,
    theme: "grid",
    headStyles: { fillColor: [106, 13, 173], textColor: [255, 255, 255] },
    body: [
      ["Patient Name", patientName],
      ["Patient ID", patientId],
      ["DOB", dob],
      ["Gender", gender],
    ],
  });

  // **DOCTOR DETAILS**
  doc.text("Doctor Details", 15, doc.autoTable.previous.finalY + 10);
  doc.autoTable({
    startY: doc.autoTable.previous.finalY + 15,
    theme: "grid",
    headStyles: { fillColor: [106, 13, 173], textColor: [255, 255, 255] },
    body: [["Doctor Name", doctorName]],
  });

  // **DIAGNOSIS**
  doc.text("Diagnosis", 15, doc.autoTable.previous.finalY + 10);
  doc.autoTable({
    startY: doc.autoTable.previous.finalY + 15,
    theme: "grid",
    headStyles: { fillColor: [106, 13, 173], textColor: [255, 255, 255] },
    body: [
      ["Predicted Disease", prediction],
      ["Confidence", `${(confidence * 100).toFixed(2)}%`],
      ["Category", category],
      ["Severity", severity],
    ],
  });

  // **SYMPTOMS**
  doc.text("Symptoms Overview", 15, doc.autoTable.previous.finalY + 10);
  doc.autoTable({
    startY: doc.autoTable.previous.finalY + 15,
    theme: "grid",
    headStyles: { fillColor: [106, 13, 173], textColor: [255, 255, 255] },
    body: symptoms.map((symptom) => [symptom]),
  });

  // **CAUSES & RISK FACTORS**
  doc.text("Possible Causes & Risk Factors", 15, doc.autoTable.previous.finalY + 10);
  doc.autoTable({
    startY: doc.autoTable.previous.finalY + 15,
    theme: "grid",
    headStyles: { fillColor: [106, 13, 173], textColor: [255, 255, 255] },
    body: causes.map((cause) => [cause.type, cause.details]),
  });

  // **TREATMENT & RECOMMENDATIONS**
  doc.text("Treatment & Recommendations", 15, doc.autoTable.previous.finalY + 10);
  doc.autoTable({
    startY: doc.autoTable.previous.finalY + 15,
    theme: "grid",
    headStyles: { fillColor: [106, 13, 173], textColor: [255, 255, 255] },
    body: treatments.map((treatment) => [treatment.type, treatment.details]),
  });

  // **DIAGNOSIS IMAGE**
  if (base64Image) {
    doc.text("Highlighted Diagnosis Image", 15, doc.autoTable.previous.finalY + 10);
    doc.addImage(base64Image, "PNG", 40, doc.autoTable.previous.finalY + 15, 130, 90);
  }

  // **FOOTER**
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Generated by Companion Care | Confidential Medical Report", 105, 285, {
    align: "center",
  });

  doc.save(`${patientName}_Medical_Report.pdf`);
};

export default generateMedicalReport;
